/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessRouteImport } from './routes/access'
import { Route as AccountRouteImport } from './routes/account'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as MoreRouteImport } from './routes/more'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as BagsIndexRouteImport } from './routes/bags.index'
import { Route as BagsBagIdRouteImport } from './routes/bags.$bagId'
import { Route as BinsIndexRouteImport } from './routes/bins.index'
import { Route as BinsBinIdRouteImport } from './routes/bins.$binId'
import { Route as RolesIndexRouteImport } from './routes/roles.index'
import { Route as RolesRoleIdRouteImport } from './routes/roles.$roleId'
import { Route as ShelvesIndexRouteImport } from './routes/shelves.index'
import { Route as ShelvesCategoryIdRouteImport } from './routes/shelves.$categoryId'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as StaffStaffIdRouteImport } from './routes/staff.$staffId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const BagsIndexRoute = BagsIndexRouteImport.update({
  id: '/bags/',
  path: '/bags/',
  getParentRoute: () => rootRouteImport,
} as any)
const BagsBagIdRoute = BagsBagIdRouteImport.update({
  id: '/bags/$bagId',
  path: '/bags/$bagId',
  getParentRoute: () => rootRouteImport,
} as any)
const BinsIndexRoute = BinsIndexRouteImport.update({
  id: '/bins/',
  path: '/bins/',
  getParentRoute: () => rootRouteImport,
} as any)
const BinsBinIdRoute = BinsBinIdRouteImport.update({
  id: '/bins/$binId',
  path: '/bins/$binId',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesIndexRoute = RolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoleIdRoute = RolesRoleIdRouteImport.update({
  id: '/roles/$roleId',
  path: '/roles/$roleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShelvesIndexRoute = ShelvesIndexRouteImport.update({
  id: '/shelves/',
  path: '/shelves/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShelvesCategoryIdRoute = ShelvesCategoryIdRouteImport.update({
  id: '/shelves/$categoryId',
  path: '/shelves/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffStaffIdRoute = StaffStaffIdRouteImport.update({
  id: '/staff/$staffId',
  path: '/staff/$staffId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/account': typeof AccountRoute
  '/callback': typeof CallbackRoute
  '/more': typeof MoreRoute
  '/welcome': typeof WelcomeRoute
  '/bags/$bagId': typeof BagsBagIdRoute
  '/bins/$binId': typeof BinsBinIdRoute
  '/roles/$roleId': typeof RolesRoleIdRoute
  '/shelves/$categoryId': typeof ShelvesCategoryIdRoute
  '/staff/$staffId': typeof StaffStaffIdRoute
  '/bags/': typeof BagsIndexRoute
  '/bins/': typeof BinsIndexRoute
  '/roles/': typeof RolesIndexRoute
  '/shelves/': typeof ShelvesIndexRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/account': typeof AccountRoute
  '/callback': typeof CallbackRoute
  '/more': typeof MoreRoute
  '/welcome': typeof WelcomeRoute
  '/bags/$bagId': typeof BagsBagIdRoute
  '/bins/$binId': typeof BinsBinIdRoute
  '/roles/$roleId': typeof RolesRoleIdRoute
  '/shelves/$categoryId': typeof ShelvesCategoryIdRoute
  '/staff/$staffId': typeof StaffStaffIdRoute
  '/bags': typeof BagsIndexRoute
  '/bins': typeof BinsIndexRoute
  '/roles': typeof RolesIndexRoute
  '/shelves': typeof ShelvesIndexRoute
  '/staff': typeof StaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/account': typeof AccountRoute
  '/callback': typeof CallbackRoute
  '/more': typeof MoreRoute
  '/welcome': typeof WelcomeRoute
  '/bags/$bagId': typeof BagsBagIdRoute
  '/bins/$binId': typeof BinsBinIdRoute
  '/roles/$roleId': typeof RolesRoleIdRoute
  '/shelves/$categoryId': typeof ShelvesCategoryIdRoute
  '/staff/$staffId': typeof StaffStaffIdRoute
  '/bags/': typeof BagsIndexRoute
  '/bins/': typeof BinsIndexRoute
  '/roles/': typeof RolesIndexRoute
  '/shelves/': typeof ShelvesIndexRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/account'
    | '/callback'
    | '/more'
    | '/welcome'
    | '/bags/$bagId'
    | '/bins/$binId'
    | '/roles/$roleId'
    | '/shelves/$categoryId'
    | '/staff/$staffId'
    | '/bags/'
    | '/bins/'
    | '/roles/'
    | '/shelves/'
    | '/staff/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access'
    | '/account'
    | '/callback'
    | '/more'
    | '/welcome'
    | '/bags/$bagId'
    | '/bins/$binId'
    | '/roles/$roleId'
    | '/shelves/$categoryId'
    | '/staff/$staffId'
    | '/bags'
    | '/bins'
    | '/roles'
    | '/shelves'
    | '/staff'
  id:
    | '__root__'
    | '/'
    | '/access'
    | '/account'
    | '/callback'
    | '/more'
    | '/welcome'
    | '/bags/$bagId'
    | '/bins/$binId'
    | '/roles/$roleId'
    | '/shelves/$categoryId'
    | '/staff/$staffId'
    | '/bags/'
    | '/bins/'
    | '/roles/'
    | '/shelves/'
    | '/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessRoute: typeof AccessRoute
  AccountRoute: typeof AccountRoute
  CallbackRoute: typeof CallbackRoute
  MoreRoute: typeof MoreRoute
  WelcomeRoute: typeof WelcomeRoute
  BagsBagIdRoute: typeof BagsBagIdRoute
  BinsBinIdRoute: typeof BinsBinIdRoute
  RolesRoleIdRoute: typeof RolesRoleIdRoute
  ShelvesCategoryIdRoute: typeof ShelvesCategoryIdRoute
  StaffStaffIdRoute: typeof StaffStaffIdRoute
  BagsIndexRoute: typeof BagsIndexRoute
  BinsIndexRoute: typeof BinsIndexRoute
  RolesIndexRoute: typeof RolesIndexRoute
  ShelvesIndexRoute: typeof ShelvesIndexRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bags/': {
      id: '/bags/'
      path: '/bags'
      fullPath: '/bags/'
      preLoaderRoute: typeof BagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bags/$bagId': {
      id: '/bags/$bagId'
      path: '/bags/$bagId'
      fullPath: '/bags/$bagId'
      preLoaderRoute: typeof BagsBagIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bins/': {
      id: '/bins/'
      path: '/bins'
      fullPath: '/bins/'
      preLoaderRoute: typeof BinsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bins/$binId': {
      id: '/bins/$binId'
      path: '/bins/$binId'
      fullPath: '/bins/$binId'
      preLoaderRoute: typeof BinsBinIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/': {
      id: '/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof RolesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/$roleId': {
      id: '/roles/$roleId'
      path: '/roles/$roleId'
      fullPath: '/roles/$roleId'
      preLoaderRoute: typeof RolesRoleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shelves/': {
      id: '/shelves/'
      path: '/shelves'
      fullPath: '/shelves/'
      preLoaderRoute: typeof ShelvesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shelves/$categoryId': {
      id: '/shelves/$categoryId'
      path: '/shelves/$categoryId'
      fullPath: '/shelves/$categoryId'
      preLoaderRoute: typeof ShelvesCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/$staffId': {
      id: '/staff/$staffId'
      path: '/staff/$staffId'
      fullPath: '/staff/$staffId'
      preLoaderRoute: typeof StaffStaffIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessRoute: AccessRoute,
  AccountRoute: AccountRoute,
  CallbackRoute: CallbackRoute,
  MoreRoute: MoreRoute,
  WelcomeRoute: WelcomeRoute,
  BagsBagIdRoute: BagsBagIdRoute,
  BinsBinIdRoute: BinsBinIdRoute,
  RolesRoleIdRoute: RolesRoleIdRoute,
  ShelvesCategoryIdRoute: ShelvesCategoryIdRoute,
  StaffStaffIdRoute: StaffStaffIdRoute,
  BagsIndexRoute: BagsIndexRoute,
  BinsIndexRoute: BinsIndexRoute,
  RolesIndexRoute: RolesIndexRoute,
  ShelvesIndexRoute: ShelvesIndexRoute,
  StaffIndexRoute: StaffIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
