// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddBagLineReducer from "../add_bag_line_reducer";
import AddCategoryReducer from "../add_category_reducer";
import AddConditionReducer from "../add_condition_reducer";
import AddGenderReducer from "../add_gender_reducer";
import AddLocationReducer from "../add_location_reducer";
import AddSizeReducer from "../add_size_reducer";
import CloseBagReducer from "../close_bag_reducer";
import CorrectCountReducer from "../correct_count_reducer";
import CreateRoleReducer from "../create_role_reducer";
import DeleteRoleReducer from "../delete_role_reducer";
import FinishWelcomeReducer from "../finish_welcome_reducer";
import GrantCapabilityReducer from "../grant_capability_reducer";
import HandOutReducer from "../hand_out_reducer";
import InviteStaffReducer from "../invite_staff_reducer";
import OpenBagReducer from "../open_bag_reducer";
import RemoveBagLineReducer from "../remove_bag_line_reducer";
import RemoveMyLoginReducer from "../remove_my_login_reducer";
import RevokeCapabilityReducer from "../revoke_capability_reducer";
import SeedInventoryReducer from "../seed_inventory_reducer";
import SetStaffActiveReducer from "../set_staff_active_reducer";
import SetStaffPersonReducer from "../set_staff_person_reducer";
import SetStaffRoleReducer from "../set_staff_role_reducer";
import UpdateCategoryReducer from "../update_category_reducer";
import UpdateConditionReducer from "../update_condition_reducer";
import UpdateGenderReducer from "../update_gender_reducer";
import UpdateLocationReducer from "../update_location_reducer";
import UpdateMyNameReducer from "../update_my_name_reducer";
import UpdateRoleReducer from "../update_role_reducer";
import UpdateSizeReducer from "../update_size_reducer";

export type AddBagLineParams = __Infer<typeof AddBagLineReducer>;
export type AddCategoryParams = __Infer<typeof AddCategoryReducer>;
export type AddConditionParams = __Infer<typeof AddConditionReducer>;
export type AddGenderParams = __Infer<typeof AddGenderReducer>;
export type AddLocationParams = __Infer<typeof AddLocationReducer>;
export type AddSizeParams = __Infer<typeof AddSizeReducer>;
export type CloseBagParams = __Infer<typeof CloseBagReducer>;
export type CorrectCountParams = __Infer<typeof CorrectCountReducer>;
export type CreateRoleParams = __Infer<typeof CreateRoleReducer>;
export type DeleteRoleParams = __Infer<typeof DeleteRoleReducer>;
export type FinishWelcomeParams = __Infer<typeof FinishWelcomeReducer>;
export type GrantCapabilityParams = __Infer<typeof GrantCapabilityReducer>;
export type HandOutParams = __Infer<typeof HandOutReducer>;
export type InviteStaffParams = __Infer<typeof InviteStaffReducer>;
export type OpenBagParams = __Infer<typeof OpenBagReducer>;
export type RemoveBagLineParams = __Infer<typeof RemoveBagLineReducer>;
export type RemoveMyLoginParams = __Infer<typeof RemoveMyLoginReducer>;
export type RevokeCapabilityParams = __Infer<typeof RevokeCapabilityReducer>;
export type SeedInventoryParams = __Infer<typeof SeedInventoryReducer>;
export type SetStaffActiveParams = __Infer<typeof SetStaffActiveReducer>;
export type SetStaffPersonParams = __Infer<typeof SetStaffPersonReducer>;
export type SetStaffRoleParams = __Infer<typeof SetStaffRoleReducer>;
export type UpdateCategoryParams = __Infer<typeof UpdateCategoryReducer>;
export type UpdateConditionParams = __Infer<typeof UpdateConditionReducer>;
export type UpdateGenderParams = __Infer<typeof UpdateGenderReducer>;
export type UpdateLocationParams = __Infer<typeof UpdateLocationReducer>;
export type UpdateMyNameParams = __Infer<typeof UpdateMyNameReducer>;
export type UpdateRoleParams = __Infer<typeof UpdateRoleReducer>;
export type UpdateSizeParams = __Infer<typeof UpdateSizeReducer>;

