// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateRoleReducer from "../create_role_reducer";
import DeleteRoleReducer from "../delete_role_reducer";
import FinishWelcomeReducer from "../finish_welcome_reducer";
import GrantCapabilityReducer from "../grant_capability_reducer";
import InviteStaffReducer from "../invite_staff_reducer";
import RemoveMyLoginReducer from "../remove_my_login_reducer";
import RevokeCapabilityReducer from "../revoke_capability_reducer";
import SetStaffActiveReducer from "../set_staff_active_reducer";
import SetStaffPersonReducer from "../set_staff_person_reducer";
import SetStaffRoleReducer from "../set_staff_role_reducer";
import UpdateMyNameReducer from "../update_my_name_reducer";
import UpdateRoleReducer from "../update_role_reducer";

export type CreateRoleParams = __Infer<typeof CreateRoleReducer>;
export type DeleteRoleParams = __Infer<typeof DeleteRoleReducer>;
export type FinishWelcomeParams = __Infer<typeof FinishWelcomeReducer>;
export type GrantCapabilityParams = __Infer<typeof GrantCapabilityReducer>;
export type InviteStaffParams = __Infer<typeof InviteStaffReducer>;
export type RemoveMyLoginParams = __Infer<typeof RemoveMyLoginReducer>;
export type RevokeCapabilityParams = __Infer<typeof RevokeCapabilityReducer>;
export type SetStaffActiveParams = __Infer<typeof SetStaffActiveReducer>;
export type SetStaffPersonParams = __Infer<typeof SetStaffPersonReducer>;
export type SetStaffRoleParams = __Infer<typeof SetStaffRoleReducer>;
export type UpdateMyNameParams = __Infer<typeof UpdateMyNameReducer>;
export type UpdateRoleParams = __Infer<typeof UpdateRoleReducer>;

