// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  eventId: __t.u64().primaryKey().name("event_id"),
  at: __t.timestamp(),
  actorName: __t.string().name("actor_name"),
  actorStaffId: __t.u64().name("actor_staff_id"),
  action: __t.string(),
  targetTable: __t.string().name("target_table"),
  targetId: __t.u64().name("target_id"),
  details: __t.string(),
});
