// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  lineId: __t.u64().primaryKey().name("line_id"),
  bagId: __t.u64().name("bag_id"),
  slotId: __t.u64().name("slot_id"),
  locationLabel: __t.string().name("location_label"),
  categoryLabel: __t.string().name("category_label"),
  sizeLabel: __t.string().name("size_label"),
  genderLabel: __t.string().name("gender_label"),
  conditionLabel: __t.string().name("condition_label"),
  count: __t.u32(),
  createdAt: __t.timestamp().name("created_at"),
});
