// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  bagId: __t.u64().primaryKey().name("bag_id"),
  kind: __t.string(),
  status: __t.string(),
  openedAt: __t.timestamp().name("opened_at"),
  openedByName: __t.string().name("opened_by_name"),
  closedAt: __t.timestamp().name("closed_at"),
  lineCount: __t.u32().name("line_count"),
  itemCount: __t.u32().name("item_count"),
  note: __t.string(),
});
