// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  key: __t.string().primaryKey(),
  slotId: __t.u64().name("slot_id"),
  locationId: __t.u64().name("location_id"),
  locationLabel: __t.string().name("location_label"),
  locationSort: __t.u32().name("location_sort"),
  categoryLabel: __t.string().name("category_label"),
  sizeLabel: __t.string().name("size_label"),
  genderLabel: __t.string().name("gender_label"),
  conditionLabel: __t.string().name("condition_label"),
  onHand: __t.i32().name("on_hand"),
});
