// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  personId: __t.u64().primaryKey().name("person_id"),
  displayName: __t.string().name("display_name"),
  email: __t.string(),
  roleKey: __t.string().name("role_key"),
  roleLabel: __t.string().name("role_label"),
});
