// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  staffId: __t.u64().primaryKey().name("staff_id"),
  personId: __t.u64().name("person_id"),
  roleKey: __t.string().name("role_key"),
  roleLabel: __t.string().name("role_label"),
  active: __t.bool(),
  capabilities: __t.array(__t.string()),
});
