// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  movementId: __t.u64().primaryKey().name("movement_id"),
  at: __t.timestamp(),
  slotId: __t.u64().name("slot_id"),
  locationLabel: __t.string().name("location_label"),
  categoryLabel: __t.string().name("category_label"),
  sizeLabel: __t.string().name("size_label"),
  genderLabel: __t.string().name("gender_label"),
  conditionLabel: __t.string().name("condition_label"),
  delta: __t.i32(),
  kind: __t.string(),
  staffName: __t.string().name("staff_name"),
  bagLineId: __t.u64().name("bag_line_id"),
  note: __t.string(),
});
