// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AccessEvent = __t.object("AccessEvent", {
  id: __t.u64(),
  at: __t.timestamp(),
  identity: __t.identity(),
  connectionId: __t.string(),
  issuer: __t.string(),
  subject: __t.string(),
  email: __t.string(),
  outcome: __t.string(),
});
export type AccessEvent = __Infer<typeof AccessEvent>;

export const AccessEventPurgeSchedule = __t.object("AccessEventPurgeSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type AccessEventPurgeSchedule = __Infer<typeof AccessEventPurgeSchedule>;

export const AccessLog = __t.object("AccessLog", {});
export type AccessLog = __Infer<typeof AccessLog>;

export const AccessLogEntry = __t.object("AccessLogEntry", {
  eventId: __t.u64(),
  at: __t.timestamp(),
  identityHex: __t.string(),
  issuer: __t.string(),
  email: __t.string(),
  outcome: __t.string(),
  displayName: __t.string(),
});
export type AccessLogEntry = __Infer<typeof AccessLogEntry>;

export const AccountDetails = __t.object("AccountDetails", {
  personId: __t.u64(),
  displayName: __t.string(),
  email: __t.string(),
  roleKey: __t.string(),
  roleLabel: __t.string(),
});
export type AccountDetails = __Infer<typeof AccountDetails>;

export const AuditEvent = __t.object("AuditEvent", {
  id: __t.u64(),
  at: __t.timestamp(),
  actorStaffId: __t.u64(),
  action: __t.string(),
  targetTable: __t.string(),
  targetId: __t.u64(),
  details: __t.string(),
});
export type AuditEvent = __Infer<typeof AuditEvent>;

export const AuthProviderLink = __t.object("AuthProviderLink", {
  id: __t.u64(),
  identity: __t.identity(),
  issuer: __t.string(),
  subject: __t.string(),
  personId: __t.u64(),
  createdAt: __t.timestamp(),
  lastSeenAt: __t.timestamp(),
});
export type AuthProviderLink = __Infer<typeof AuthProviderLink>;

export const Bag = __t.object("Bag", {
  id: __t.u64(),
  kind: __t.string(),
  status: __t.string(),
  openedAt: __t.timestamp(),
  openedBy: __t.u64(),
  closedAt: __t.timestamp(),
  closedBy: __t.u64(),
  donorPersonId: __t.u64(),
  note: __t.string(),
});
export type Bag = __Infer<typeof Bag>;

export const BagLine = __t.object("BagLine", {
  id: __t.u64(),
  bagId: __t.u64(),
  slotId: __t.u64(),
  count: __t.u32(),
  createdAt: __t.timestamp(),
  createdBy: __t.u64(),
  locationId: __t.u64(),
});
export type BagLine = __Infer<typeof BagLine>;

export const BagLineEntry = __t.object("BagLineEntry", {
  lineId: __t.u64(),
  bagId: __t.u64(),
  slotId: __t.u64(),
  locationLabel: __t.string(),
  categoryLabel: __t.string(),
  sizeLabel: __t.string(),
  genderLabel: __t.string(),
  conditionLabel: __t.string(),
  count: __t.u32(),
  createdAt: __t.timestamp(),
});
export type BagLineEntry = __Infer<typeof BagLineEntry>;

export const BagLines = __t.object("BagLines", {});
export type BagLines = __Infer<typeof BagLines>;

export const BagList = __t.object("BagList", {});
export type BagList = __Infer<typeof BagList>;

export const BagSummary = __t.object("BagSummary", {
  bagId: __t.u64(),
  kind: __t.string(),
  status: __t.string(),
  openedAt: __t.timestamp(),
  openedByName: __t.string(),
  closedAt: __t.timestamp(),
  lineCount: __t.u32(),
  itemCount: __t.u32(),
  note: __t.string(),
});
export type BagSummary = __Infer<typeof BagSummary>;

export const BinLevel = __t.object("BinLevel", {
  key: __t.string(),
  slotId: __t.u64(),
  locationId: __t.u64(),
  locationLabel: __t.string(),
  locationSort: __t.u32(),
  categoryLabel: __t.string(),
  sizeLabel: __t.string(),
  genderLabel: __t.string(),
  conditionLabel: __t.string(),
  onHand: __t.i32(),
});
export type BinLevel = __Infer<typeof BinLevel>;

export const BinLevels = __t.object("BinLevels", {});
export type BinLevels = __Infer<typeof BinLevels>;

export const Category = __t.object("Category", {
  id: __t.u64(),
  label: __t.string(),
  scaleId: __t.u64(),
  sortOrder: __t.u32(),
  active: __t.bool(),
});
export type Category = __Infer<typeof Category>;

export const CategoryOption = __t.object("CategoryOption", {
  categoryId: __t.u64(),
  label: __t.string(),
  scaleId: __t.u64(),
  sortOrder: __t.u32(),
  active: __t.bool(),
});
export type CategoryOption = __Infer<typeof CategoryOption>;

export const CategoryOptions = __t.object("CategoryOptions", {});
export type CategoryOptions = __Infer<typeof CategoryOptions>;

export const Condition = __t.object("Condition", {
  id: __t.u64(),
  label: __t.string(),
  sortOrder: __t.u32(),
  active: __t.bool(),
  shelved: __t.bool(),
});
export type Condition = __Infer<typeof Condition>;

export const ConditionOption = __t.object("ConditionOption", {
  conditionId: __t.u64(),
  label: __t.string(),
  sortOrder: __t.u32(),
  active: __t.bool(),
  shelved: __t.bool(),
});
export type ConditionOption = __Infer<typeof ConditionOption>;

export const ConditionOptions = __t.object("ConditionOptions", {});
export type ConditionOptions = __Infer<typeof ConditionOptions>;

export const Gender = __t.object("Gender", {
  id: __t.u64(),
  label: __t.string(),
  sortOrder: __t.u32(),
  active: __t.bool(),
});
export type Gender = __Infer<typeof Gender>;

export const GenderOption = __t.object("GenderOption", {
  genderId: __t.u64(),
  label: __t.string(),
  sortOrder: __t.u32(),
  active: __t.bool(),
});
export type GenderOption = __Infer<typeof GenderOption>;

export const GenderOptions = __t.object("GenderOptions", {});
export type GenderOptions = __Infer<typeof GenderOptions>;

export const LedgerEntry = __t.object("LedgerEntry", {
  movementId: __t.u64(),
  at: __t.timestamp(),
  slotId: __t.u64(),
  locationLabel: __t.string(),
  categoryLabel: __t.string(),
  sizeLabel: __t.string(),
  genderLabel: __t.string(),
  conditionLabel: __t.string(),
  delta: __t.i32(),
  kind: __t.string(),
  staffName: __t.string(),
  bagLineId: __t.u64(),
  note: __t.string(),
});
export type LedgerEntry = __Infer<typeof LedgerEntry>;

export const Location = __t.object("Location", {
  id: __t.u64(),
  label: __t.string(),
  labelCode: __t.string(),
  sortOrder: __t.u32(),
  active: __t.bool(),
});
export type Location = __Infer<typeof Location>;

export const LocationOption = __t.object("LocationOption", {
  locationId: __t.u64(),
  label: __t.string(),
  sortOrder: __t.u32(),
  active: __t.bool(),
});
export type LocationOption = __Infer<typeof LocationOption>;

export const LocationOptions = __t.object("LocationOptions", {});
export type LocationOptions = __Infer<typeof LocationOptions>;

export const LoginEntry = __t.object("LoginEntry", {
  linkId: __t.u64(),
  label: __t.string(),
  createdAt: __t.timestamp(),
  lastSeenAt: __t.timestamp(),
  current: __t.bool(),
});
export type LoginEntry = __Infer<typeof LoginEntry>;

export const MyAccount = __t.object("MyAccount", {});
export type MyAccount = __Infer<typeof MyAccount>;

export const MyLogins = __t.object("MyLogins", {});
export type MyLogins = __Infer<typeof MyLogins>;

export const MyRecentSignIns = __t.object("MyRecentSignIns", {});
export type MyRecentSignIns = __Infer<typeof MyRecentSignIns>;

export const MyStaff = __t.object("MyStaff", {});
export type MyStaff = __Infer<typeof MyStaff>;

export const Person = __t.object("Person", {
  id: __t.u64(),
  displayName: __t.string(),
  email: __t.string(),
  notes: __t.string(),
  createdAt: __t.timestamp(),
});
export type Person = __Infer<typeof Person>;

export const Role = __t.object("Role", {
  id: __t.u64(),
  key: __t.string(),
  label: __t.string(),
  description: __t.string(),
  system: __t.bool(),
  createdAt: __t.timestamp(),
});
export type Role = __Infer<typeof Role>;

export const RoleCapability = __t.object("RoleCapability", {
  id: __t.u64(),
  roleId: __t.u64(),
  capability: __t.string(),
});
export type RoleCapability = __Infer<typeof RoleCapability>;

export const RoleCapabilityCell = __t.object("RoleCapabilityCell", {
  key: __t.string(),
  roleId: __t.u64(),
  capability: __t.string(),
  group: __t.string(),
  label: __t.string(),
  protected: __t.bool(),
  granted: __t.bool(),
});
export type RoleCapabilityCell = __Infer<typeof RoleCapabilityCell>;

export const RoleCapabilityMatrix = __t.object("RoleCapabilityMatrix", {});
export type RoleCapabilityMatrix = __Infer<typeof RoleCapabilityMatrix>;

export const RoleOption = __t.object("RoleOption", {
  roleId: __t.u64(),
  key: __t.string(),
  label: __t.string(),
  description: __t.string(),
  system: __t.bool(),
  protected: __t.bool(),
  holders: __t.u32(),
});
export type RoleOption = __Infer<typeof RoleOption>;

export const RoleOptions = __t.object("RoleOptions", {});
export type RoleOptions = __Infer<typeof RoleOptions>;

export const Scale = __t.object("Scale", {
  id: __t.u64(),
  key: __t.string(),
  label: __t.string(),
});
export type Scale = __Infer<typeof Scale>;

export const ScaleOption = __t.object("ScaleOption", {
  scaleId: __t.u64(),
  key: __t.string(),
  label: __t.string(),
});
export type ScaleOption = __Infer<typeof ScaleOption>;

export const ScaleOptions = __t.object("ScaleOptions", {});
export type ScaleOptions = __Infer<typeof ScaleOptions>;

export const ShelfCell = __t.object("ShelfCell", {
  slotId: __t.u64(),
  categoryId: __t.u64(),
  sizeId: __t.u64(),
  genderId: __t.u64(),
  conditionId: __t.u64(),
  categoryLabel: __t.string(),
  sizeLabel: __t.string(),
  genderLabel: __t.string(),
  conditionLabel: __t.string(),
  categorySort: __t.u32(),
  sizeSort: __t.u32(),
  genderSort: __t.u32(),
  conditionSort: __t.u32(),
  shelved: __t.bool(),
  onHand: __t.i32(),
  binCount: __t.u32(),
});
export type ShelfCell = __Infer<typeof ShelfCell>;

export const Shelves = __t.object("Shelves", {});
export type Shelves = __Infer<typeof Shelves>;

export const SignInEntry = __t.object("SignInEntry", {
  eventId: __t.u64(),
  at: __t.timestamp(),
  loginLabel: __t.string(),
  outcome: __t.string(),
});
export type SignInEntry = __Infer<typeof SignInEntry>;

export const Size = __t.object("Size", {
  id: __t.u64(),
  scaleId: __t.u64(),
  label: __t.string(),
  sortOrder: __t.u32(),
  active: __t.bool(),
});
export type Size = __Infer<typeof Size>;

export const SizeOption = __t.object("SizeOption", {
  sizeId: __t.u64(),
  scaleId: __t.u64(),
  label: __t.string(),
  sortOrder: __t.u32(),
  active: __t.bool(),
});
export type SizeOption = __Infer<typeof SizeOption>;

export const SizeOptions = __t.object("SizeOptions", {});
export type SizeOptions = __Infer<typeof SizeOptions>;

export const Slot = __t.object("Slot", {
  id: __t.u64(),
  key: __t.string(),
  categoryId: __t.u64(),
  sizeId: __t.u64(),
  genderId: __t.u64(),
  conditionId: __t.u64(),
});
export type Slot = __Infer<typeof Slot>;

export const StaffDirectory = __t.object("StaffDirectory", {});
export type StaffDirectory = __Infer<typeof StaffDirectory>;

export const StaffDirectoryEntry = __t.object("StaffDirectoryEntry", {
  staffId: __t.u64(),
  personId: __t.u64(),
  displayName: __t.string(),
  email: __t.string(),
  roleKey: __t.string(),
  roleLabel: __t.string(),
  active: __t.bool(),
  invitedAt: __t.timestamp(),
  hasSignedIn: __t.bool(),
  lastSeenAt: __t.timestamp(),
  welcomed: __t.bool(),
});
export type StaffDirectoryEntry = __Infer<typeof StaffDirectoryEntry>;

export const StaffMember = __t.object("StaffMember", {
  id: __t.u64(),
  personId: __t.u64(),
  roleId: __t.u64(),
  active: __t.bool(),
  invitedAt: __t.timestamp(),
  invitedBy: __t.u64(),
  welcomedAt: __t.timestamp(),
});
export type StaffMember = __Infer<typeof StaffMember>;

export const StaffStanding = __t.object("StaffStanding", {
  staffId: __t.u64(),
  personId: __t.u64(),
  displayName: __t.string(),
  roleKey: __t.string(),
  roleLabel: __t.string(),
  roleDescription: __t.string(),
  active: __t.bool(),
  capabilities: __t.array(__t.string()),
  capabilityLabels: __t.array(__t.string()),
  welcomed: __t.bool(),
});
export type StaffStanding = __Infer<typeof StaffStanding>;

export const StockBinLevel = __t.object("StockBinLevel", {
  key: __t.string(),
  slotId: __t.u64(),
  locationId: __t.u64(),
  onHand: __t.i32(),
});
export type StockBinLevel = __Infer<typeof StockBinLevel>;

export const StockLedger = __t.object("StockLedger", {});
export type StockLedger = __Infer<typeof StockLedger>;

export const StockLevel = __t.object("StockLevel", {
  slotId: __t.u64(),
  onHand: __t.i32(),
});
export type StockLevel = __Infer<typeof StockLevel>;

export const StockMovement = __t.object("StockMovement", {
  id: __t.u64(),
  slotId: __t.u64(),
  delta: __t.i32(),
  kind: __t.string(),
  at: __t.timestamp(),
  staffId: __t.u64(),
  bagLineId: __t.u64(),
  itemId: __t.u64(),
  note: __t.string(),
  locationId: __t.u64(),
});
export type StockMovement = __Infer<typeof StockMovement>;

